config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users
  resources :collections do
    member do
      get 'delete'
    end
  end

  resources :collections do
    resources :books, :movies, :electronics, :albums do
      member do
        get 'delete'
      end
    end
  end

  match ':controller(/:action(/:id))', :via => [:get, :post, :put, :delete]

  root to: 'home#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :collection
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :collection
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :books, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :electronics, dependent: :destroy
  has_many :albums, dependent: :destroy

  validates :user_id, presence: true
end

app/models/electronic.rb
class Electronic < ActiveRecord::Base
  belongs_to :collection
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :collection
end

app/models/user.rb
class User < ActiveRecord::Base
  # before_action :authenticate_user!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable


  has_many :collections
  # belongs_to :collection

  validates :username, uniqueness: true, format: { with: /\A[a-zA-z0-9]+\z/, message: "username can only contain letters and numbers" }
  validates_presence_of :email

  def to_param
    username
  end


  def self.find_for_database_authentication(conditions={})
    self.find_by(username: conditions[:email]) ||
    self.find_by(email: conditions[:email])
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.where(collection_id: params[:collection_id]).all
  end

  def create
    @album = @collection.albums.new(album_params)
    if @album.save
      redirect_to(action: :index)
    else
      render :new
    end
  end

  def new
    @album = Album.new
  end

  def show
    album
  end

  def delete
    album
  end

  def destroy
    album.destroy
    flash[:notice] = "#{@album.title} was deleted successfully."
    redirect_to(action: :index)
  end

  private

  def album
    @album ||= Album.find_by_id(params[:id])
  end

  def album_params
    params.require(:album).permit(:title, :artist, :genre, :rating, :collection_id, :id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :find_username
  before_filter :find_collection

  private

  def find_username
    return unless current_user
    @username ||= current_user.username
  end

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
   devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
  end

  def find_collection
    return unless params[:collection_id]
    @collection ||= Collection.find(params[:collection_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.where(collection_id: params[:collection_id])
  end

  def create
    @book = @collection.books.new(book_params)
    if @book.save
      redirect_to(action: :index)
    else
      render :new
    end
  end

  def new
    @book = Book.new
  end

  def show
    book
  end

  def delete
    book
  end

  def destroy
    book.destroy
    flash[:notice] = "#{@book.title} was deleted successfully."
    redirect_to(action: :index)
  end

  private

  def book
    @book ||= Book.find_by_id(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :genre, :rating, :collection_id, :id)
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter :find_collection

  def index
    @collections = current_user.collections
    if current_user.collections.empty?
      @no_collection = "There are currently no collections for this user. Please create one."
    end
    @user = current_user.username
  end

  def new
    @user = current_user.username
    @collection = Collection.new
  end

  def create
    @collection = current_user.collections.new(collection_params)
    if @collection.save
      redirect_to collections_path
    else
      render :new
    end
  end

  def destroy
    @collection.destroy
    flash[:notice] = "#{@collection.title} was deleted successfully."
    redirect_to(action: :index)
  end

  def update
    if @collection.update_attributes(collection_params)
      flash[:notice] = "Collection updated successfully"
      redirect_to(action: :index)
    else
      render :edit
    end
  end

  private

  def find_collection
    @collection ||= Collection.find_by_id(params[:id])
  end

  def collection_params
    params.require(:collection).permit(:title, :user, :created_by, :book)
  end
end

app/controllers/electronics_controller.rb
class ElectronicsController < ApplicationController

  def index
    @electronics = Electronic.where(collection_id: params[:collection_id])
  end

  def create
    @electronic = @collection.electronics.new(electronic_params)
    if @electronic.save
      redirect_to(action: :index)
    else
      render :new
    end
  end

  def new
    @electronic = Electronic.new
  end

  def show
    electronic
  end

  def delete
    electronic
  end

  def destroy
    electronic.destroy
    flash[:notice] = "#{@electronic.name} was deleted successfully."
    redirect_to(action: :index)
  end

  private

  def electronic
    @electronic ||= Electronic.find_by_id(params[:id])
  end

  def electronic_params
    params.require(:electronic).permit(:name, :serial, :collection_id, :id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.where(collection_id: params[:collection_id])
  end

  def create
    @movie = @collection.movies.new(movie_params)
    if @movie.save
      redirect_to(action: :index)
    else
      render :new
    end
  end

  def new
    @movie = Movie.new
  end

  def show
    movie
  end

  def delete
    movie
  end

  def destroy
    movie.destroy
    flash[:notice] = "#{@movie.title} was deleted successfully."
    redirect_to(action: :index)
  end

  private
  def movie
    @movie ||= Movie.find_by_id(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :director, :genre, :rating, :collection_id, :id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # @user = User.find_by_username(params[:id])
    render :index
  end

  def show
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/electronic_helper.rb
module ElectronicHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/delete.html.haml
#delete_container.albums
  .back_button= link_to("Return to albums", {action: "index"})
  %h2 Delete album
  %p Are you certain you want to delete #{@album.title}?
  = button_to("Delete album", collection_album_path(id: @album.id, collection_id: @collection.id), method: :delete)

app/views/albums/index.html.haml
#albums_for.albums
  .back_button= link_to("Return to collections", collection_path(id: @collection.id))
  -# %h1 Albums in #{current_user.username.capitalize}'s collection:
  %h1 - Albums -
  %h3 #{@no_albums}
  .albums_box
    - @albums.each do |album|
      .album_box
        %h3.album_list= link_to('"'+album.title+'"', collection_album_path(collection_id: @collection.id, id: album.id))
    %button#add_album.add_button= link_to("Add album", new_collection_album_path(collection_id: @collection.id))

app/views/albums/new.html.haml
#new_album_wrap.albums
  .back_button= link_to("Return to collections", {controller: "Collections", action: "index"})
  %h2 New album
  = form_for(:album, html: {:multipart => true}, :url => {:action => "create"} ) do |f|
    %h3#album_title Title
    = f.text_field(:title, as: :string, autofocus: "true", placeholder: "title", maxlength: 100)
    %h3#album_author Author
    = f.text_field(:artist, as: :string, placeholder: "artist", maxlength: 50)
    %h3#album_genre Genre
    = f.text_field(:genre, as: :string, placeholder: "genre", maxlength: 50)
    %h3#album_rating Rating
    = f.text_field(:rating, as: :string, placeholder: "pick a number between 1 and 5", maxlength: 50)
    #user= f.hidden_field(:created_by, :value => current_user.username)
    #create_button
      = submit_tag("Create album")

app/views/albums/show.html.haml
#show_album.albums
  .back_button= link_to("Return to albums", {action: "index"})
  %h2 "#{@album.title}"
  %h4 Artist: #{@album.artist}
  %h4 Genre: #{@album.genre}
  %h4 Rating: #{@album.rating}
  -# .edit= link_to("Edit",  {action: "edit", id: "album.id"})
  .delete= link_to("Delete",  delete_collection_album_path(id: @album.id, collection_id: @collection.id))

app/views/books/delete.html.haml
#delete_container.books
  .back_button= link_to("Return to books", {action: "index"})
  %h2 Delete book
  %p Are you certain you want to delete #{@book.title}?
  = button_to("Delete book", collection_book_path(id: @book.id, collection_id: @collection.id), method: :delete)

app/views/books/index.html.haml
#books_for.books
  .back_button= link_to("Return to collections", collection_path(id: @collection.id))
  %h1 - Books -
  %h3 #{@no_books}
  .books_box
    - @books.each do |book|
      .book_box
        %h3.book_list= link_to('"'+book.title+'"', collection_book_path(collection_id: @collection.id, id: book.id))
    %button#add_book.add_button= link_to("Add book", new_collection_book_path(collection_id: @collection.id))

app/views/books/new.html.haml
#new_book_wrap.books
  .back_button= link_to("Return to collections", {controller: "Collections", action: "index"})
  %h2 New book
  = form_for(:book, html: {:multipart => true}, :url => {:action => "create"} ) do |f|
    %h3#book_title Title
    = f.text_field(:title, as: :string, autofocus: "true", placeholder: "title", maxlength: 100)
    %h3#book_author Author
    = f.text_field(:author, as: :string, placeholder: "author", maxlength: 50)
    %h3#book_genre Genre
    = f.text_field(:genre, as: :string, placeholder: "genre", maxlength: 50)
    %h3#book_rating Rating
    = f.text_field(:rating, as: :string, placeholder: "pick a number between 1 and 5", maxlength: 50)
    #user= f.hidden_field(:created_by, :value => current_user.username)
    #create_button
      = submit_tag("Create book")

app/views/books/show.html.haml
#show_book.books
  .back_button= link_to("Return to books", {action: "index"})
  %h2 "#{@book.title}"
  %h4 Author: #{@book.author}
  %h4 Genre: #{@book.genre}
  %h4 Rating: #{@book.rating}
  -# .edit= link_to("Edit",  {action: "edit", id: @book.id})
  .delete= link_to("Delete",  {:action => 'delete', :id => @book.id, :collection_id => @collection.id})

app/views/collections/delete.html.haml
#delete_container.collections
  .back_button= link_to("Return to collections", {action: "index"})
  %h2 Delete collection
  %p Are you certain you want to delete #{@collection.title}?
  = button_to("Delete collection", {controller: "Collections", action: "destroy", id: @collection.id})

app/views/collections/edit.html.haml
#edit_container.collections
  .back_button= link_to("Return to collections", {:action => "index"})
  %h2 Edit collection
  = simple_form_for(@collection) do |f|
    %h2 Title
    = f.text_field(:title, as: :string, autofocus: "true", maxlength: 50)
    #user= f.hidden_field(:created_by, :value => current_user.username)
    #edit_button
      = submit_tag("Update collection")

app/views/collections/index.html.haml
#collection_for.collections
  %h1 Collections for #{@username.capitalize}
  %h3 #{@no_collection}
  - @collections.each do |col|
    .collection_box
      %h2.col= '- ' + col.title + ' -'
      %span
        .show= link_to("Show", collection_path(id: col.id))
        .edit= link_to("Edit", edit_collection_path(id: col.id))
        .delete= link_to("Delete",  delete_collection_path(id: col.id))

app/views/collections/new.html.haml
#new_collection_wrap.collections
  %h2 New collection
  = simple_form_for(@collection) do |f|
    %h3#collection_title Collection Name
    = f.text_field(:title, as: :string, autofocus: "true", placeholder: "title", maxlength: 100)
    #user= f.hidden_field(:created_by, :value => current_user.username)
    #create_button
      = submit_tag("Create collection")

app/views/collections/show.html.haml
#show_container.collections
  .back_button= link_to("Return to collections",collection_path(id: @collection.id))
  -# %h2 #{@collection.created_by.capitalize}'s #{@collection.title.downcase} collection
  %h2 #{@collection.title.capitalize} collection
  .item_box
    #book_button= link_to("Books", collection_books_path(collection_id: @collection.id))
    #movie_button= link_to("Movies", collection_movies_path(collection_id: @collection.id))
    #music_button= link_to("Albums", collection_albums_path(collection_id: @collection.id))
    #electronic_button= link_to("Electronics", collection_electronics_path(collection_id: @collection.id))

app/views/electronics/delete.html.haml
#delete_container.electronics
  .back_button= link_to("Return to electronics", {action: "index"})
  %h2 Delete electronic
  %p Are you certain you want to delete #{@electronic.name}?
  = button_to("Delete electronic", collection_electronic_path(id: @electronic.id, collection_id: @collection.id), method: :delete)

app/views/electronics/index.html.haml
#electronics_for.electronics
  .back_button= link_to("Return to collections", {controller: "Collections", action: "index"})
  -# %h1 Electronics in #{current_user.username.capitalize}'s collection:
  %h1 - Electronics -
  %h3 #{@no_electronics}
  .electronics_box
    - @electronics.each do |electronic|
      .electronic_box
        %h3.electronic_list= link_to('"'+electronic.name+'"', collection_electronic_path(id: electronic.id, collection_id: @collection.id))
    %button#add_electronic.add_electronic= link_to("Add electronic", new_collection_electronic_path(collection_id: @collection.id))

app/views/electronics/new.html.haml
#new_electronic_wrap.electronics
  .back_button= link_to("Return to collections", {controller: "Collections", action: "index"})
  %h2 New electronic
  = form_for(:electronic, html: {:multipart => true}, :url => {:action => "create"} ) do |f|
    %h3#electronic_title Name
    = f.text_field(:name, as: :string, autofocus: "true", placeholder: "name", maxlength: 100)
    %h3#electronic_author Serial number
    = f.text_field(:serial, as: :string, placeholder: "serial number", maxlength: 50)
    #user= f.hidden_field(:created_by, :value => current_user.username)
    #create_button
      = submit_tag("Create electronic")

app/views/electronics/show.html.haml
#show_electronic.electronics
  .back_button= link_to("Return to electronics", {action: "index"})
  %h2 Name: #{@electronic.name}
  %h4 Serial number: #{@electronic.serial}
  -# .edit= link_to("Edit",  {action: "edit", id: @electronic.id})
  .delete= link_to("Delete",  delete_collection_electronic_path(id: @electronic.id, collection_id: @collection.id))

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title What I Got
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
  %body
    %header
      %ul.main_navigation
        %h4#welcome_tag Welcome to
        %h1#title_tag What I Got
        %h4.show-for-large-up#tagline your home media manager
        .devise_navigation
          -unless user_signed_in?
            %li= link_to "Sign up", new_user_registration_path
          -if user_signed_in?
            %li= link_to 'Sign out', destroy_user_session_path, method: 'delete'
          -else
            %li= link_to 'Sign in', new_user_session_path
        - if user_signed_in?
          %li.action_my_collections= link_to("View collections", collections_path )
          %li.action_my_collections= link_to("New collection", new_collection_path )
          %li
            %h2#user Logged in as: #{@username.capitalize}
    .alert= alert
    .notice= notice
    = yield

app/views/movies/delete.html.haml
#delete_container.movies
  .back_button= link_to("Return to movies", {action: "index"})
  %h2 Delete movie
  %p Are you certain you want to delete #{@movie.title}?
  = button_to("Delete movie", collection_movie_path(id: @movie.id, collection_id: @collection.id), method: :delete)

app/views/movies/index.html.haml
#movies_for.movies
  .back_button= link_to("Return to collection", collection_path(id: @collection.id))
  -# %h1 Movies in #{current_user.username.capitalize}'s collection:
  %h1 - Movies -
  %h3 #{@no_books}
  .movies_box
    - @movies.each do |movie|
      .movie_box
        %h3.movie_list= link_to('"'+movie.title+'"', {action: "show", id: movie.id})
    %button#add_movie.add_button= link_to("Add movie", new_collection_movie_path(collection_id: @collection.id))

app/views/movies/new.html.haml
#new_movie_wrap.movies
  .back_button= link_to("Return to collections", {controller: "Collections", action: "index"})
  %h2 New movie
  = form_for(:movie, html: {:multipart => true}, :url => {:action => "create"} ) do |f|
    %h3#book_title Title
    = f.text_field(:title, as: :string, autofocus: "true", placeholder: "title", maxlength: 100)
    %h3#book_author Director
    = f.text_field(:director, as: :string, placeholder: "director", maxlength: 50)
    %h3#book_genre Genre
    = f.text_field(:genre, as: :string, placeholder: "genre", maxlength: 50)
    %h3#book_rating Rating
    = f.text_field(:rating, as: :string, placeholder: "pick a number between 1 and 5", maxlength: 50)
    #user= f.hidden_field(:created_by, :value => current_user.username)
    #create_button
      = submit_tag("Create movie")

app/views/movies/show.html.haml
#show_movie.movies
  .back_button= link_to("Return to movies", collection_movies_path(collection_id: @collection.id))
  %h2 "#{@movie.title}"
  %h4 Director: #{@movie.director}
  %h4 Genre: #{@movie.genre}
  %h4 Rating: #{@movie.rating}
  -# .edit= link_to("Edit",  {action: "edit", id: @movie.id})
  .delete= link_to("Delete",  delete_collection_movie_path(id: @movie.id, collection_id: @collection.id))

app/views/users/index.html.haml
%h1 Users#index